version: '3'

services:
  app:
    image: albertomurrodrigo/mdas-web-alberto_mur_app
    stdin_open: true
    tty: true
    container_name: app
    ports:
      - "8081:8081"
    networks:
      mynetwork:
        ipv4_address: 172.0.0.4
networks:
  mynetwork:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.0.0.0/24